### ISSUE TITLE
Incorrect Output File Format

### ISSUE THREAD

**Issue by playful1510** [AIF-development-team/adsorptioninformationformat#37]
When clicking on the download link for my generated .AIF file, it downloads as expected, but the file format is .AIFF rather than .AIF. This persists across re-uploads of the file, refreshes of the page, and trying to right-click>'save link as'. After opening the file in Notepad++, all the information is there, simply the extension is wrong.

This happens on Firefox 117.0.1, with a Micromeritics XLS file.

**Comment by jackevansadl** [comment]
I have been unable to recreate this problem on macOS 13.5.2 on either Safari, Chrome or Firefox.

**Comment by playful1510** [comment]
Issue continues to be observed on Windows 10 22H2. 
![image](https://github.com/AIF-development-team/adsorptioninformationformat/assets/5361114/84ff3fcd-88ee-40c7-bc84-b4d505822946)
